// <auto-generated />
using System;
using FallenFaction.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FallenFaction.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250616190421_RemoveFirstNameLastName01")]
    partial class RemoveFirstNameLastName01
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AppUserTeam", b =>
                {
                    b.Property<string>("MembersId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("TeamsId")
                        .HasColumnType("int");

                    b.HasKey("MembersId", "TeamsId");

                    b.HasIndex("TeamsId");

                    b.ToTable("AppUserTeams", (string)null);
                });

            modelBuilder.Entity("ArtistPendingTitle", b =>
                {
                    b.Property<int>("ArtistsId")
                        .HasColumnType("int");

                    b.Property<int>("PendingTitlesId")
                        .HasColumnType("int");

                    b.HasKey("ArtistsId", "PendingTitlesId");

                    b.HasIndex("PendingTitlesId");

                    b.ToTable("PendingTitleArtists", (string)null);
                });

            modelBuilder.Entity("ArtistTitle", b =>
                {
                    b.Property<int>("ArtistsId")
                        .HasColumnType("int");

                    b.Property<int>("TitlesId")
                        .HasColumnType("int");

                    b.HasKey("ArtistsId", "TitlesId");

                    b.HasIndex("TitlesId");

                    b.ToTable("TitleArtists", (string)null);
                });

            modelBuilder.Entity("AuthorPendingTitle", b =>
                {
                    b.Property<int>("AuthorsId")
                        .HasColumnType("int");

                    b.Property<int>("PendingTitlesId")
                        .HasColumnType("int");

                    b.HasKey("AuthorsId", "PendingTitlesId");

                    b.HasIndex("PendingTitlesId");

                    b.ToTable("PendingTitleAuthors", (string)null);
                });

            modelBuilder.Entity("AuthorTitle", b =>
                {
                    b.Property<int>("AuthorsId")
                        .HasColumnType("int");

                    b.Property<int>("TitlesId")
                        .HasColumnType("int");

                    b.HasKey("AuthorsId", "TitlesId");

                    b.HasIndex("TitlesId");

                    b.ToTable("TitleAuthors", (string)null);
                });

            modelBuilder.Entity("CategoryPendingTitle", b =>
                {
                    b.Property<int>("CategoriesId")
                        .HasColumnType("int");

                    b.Property<int>("PendingTitlesId")
                        .HasColumnType("int");

                    b.HasKey("CategoriesId", "PendingTitlesId");

                    b.HasIndex("PendingTitlesId");

                    b.ToTable("PendingTitleCategories", (string)null);
                });

            modelBuilder.Entity("CategoryTitle", b =>
                {
                    b.Property<int>("CategoriesId")
                        .HasColumnType("int");

                    b.Property<int>("TitlesId")
                        .HasColumnType("int");

                    b.HasKey("CategoriesId", "TitlesId");

                    b.HasIndex("TitlesId");

                    b.ToTable("TitleCategories", (string)null);
                });

            modelBuilder.Entity("FallenFaction.Server.Data.Models.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsBannedFromComments")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastActive")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastLoginDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ProfilePicturePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SocialMediaLinks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("FallenFaction.Server.Data.Models.ApprovedTitleChange", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdminComment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ChangeType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsAutoApproved")
                        .HasColumnType("bit");

                    b.Property<string>("NewValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReviewedByUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("TitleId")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedByUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ReviewedByUserId");

                    b.HasIndex("TitleId");

                    b.HasIndex("UpdatedByUserId");

                    b.ToTable("ApprovedTitleChanges");
                });

            modelBuilder.Entity("FallenFaction.Server.Data.Models.Artist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OtherName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RejectedTitleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RejectedTitleId");

                    b.ToTable("Artists");
                });

            modelBuilder.Entity("FallenFaction.Server.Data.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OtherName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RejectedTitleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RejectedTitleId");

                    b.ToTable("Authors");
                });

            modelBuilder.Entity("FallenFaction.Server.Data.Models.Bookmark", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("FolderId")
                        .HasColumnType("int");

                    b.Property<int>("LastReadChapter")
                        .HasColumnType("int");

                    b.Property<int>("TitleId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("FolderId");

                    b.HasIndex("TitleId");

                    b.HasIndex("UserId");

                    b.ToTable("Bookmarks");
                });

            modelBuilder.Entity("FallenFaction.Server.Data.Models.BookmarkFolder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("BookmarkFolders");
                });

            modelBuilder.Entity("FallenFaction.Server.Data.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RejectedTitleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RejectedTitleId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Adventure"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Fantasy"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Horror"
                        });
                });

            modelBuilder.Entity("FallenFaction.Server.Data.Models.Chapter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChapterNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TeamId")
                        .HasColumnType("int");

                    b.Property<int>("TitleId")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedByUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("VolumeNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.HasIndex("TitleId");

                    b.HasIndex("UpdatedByUserId");

                    b.ToTable("Chapters");
                });

            modelBuilder.Entity("FallenFaction.Server.Data.Models.ChapterImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ChapterId")
                        .HasColumnType("int");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<int?>("PendingChapterId")
                        .HasColumnType("int");

                    b.Property<int?>("RejectedChapterId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChapterId");

                    b.HasIndex("PendingChapterId");

                    b.HasIndex("RejectedChapterId");

                    b.ToTable("ChapterImages");
                });

            modelBuilder.Entity("FallenFaction.Server.Data.Models.ChapterView", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChapterId")
                        .HasColumnType("int");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("ViewDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ChapterId");

                    b.HasIndex("UserId");

                    b.ToTable("ChapterView");
                });

            modelBuilder.Entity("FallenFaction.Server.Data.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ChapterId")
                        .HasColumnType("int");

                    b.Property<int?>("ChapterImageId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DislikesCount")
                        .HasColumnType("int");

                    b.Property<int>("LikesCount")
                        .HasColumnType("int");

                    b.Property<int?>("ParentCommentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PostedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TitleId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ChapterId");

                    b.HasIndex("ChapterImageId");

                    b.HasIndex("ParentCommentId");

                    b.HasIndex("TitleId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("FallenFaction.Server.Data.Models.CommentReaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CommentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsLike")
                        .HasColumnType("bit");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CommentId");

                    b.HasIndex("UserId", "CommentId")
                        .IsUnique();

                    b.ToTable("CommentReactions");
                });

            modelBuilder.Entity("FallenFaction.Server.Data.Models.Format", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RejectedTitleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RejectedTitleId");

                    b.ToTable("Formats");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Digital"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Print"
                        });
                });

            modelBuilder.Entity("FallenFaction.Server.Data.Models.PendingChapter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChapterNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.Property<int>("TitleId")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedByUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("VolumeNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.HasIndex("TitleId");

                    b.HasIndex("UpdatedByUserId");

                    b.ToTable("PendingChapters");
                });

            modelBuilder.Entity("FallenFaction.Server.Data.Models.PendingTitle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AgeRestriction")
                        .HasColumnType("int");

                    b.Property<string>("AlternativeNames")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BackgroundImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoverImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnglishTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExternalLinksSerialized")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OriginalTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReleaseDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatusTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatusTranslation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PendingTitles");
                });

            modelBuilder.Entity("FallenFaction.Server.Data.Models.PendingTitleChange", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdminComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChangeType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("NewValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("RequiresReview")
                        .HasColumnType("bit");

                    b.Property<int>("TitleId")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedByUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("TitleId");

                    b.HasIndex("UpdatedByUserId");

                    b.ToTable("PendingTitleChanges");
                });

            modelBuilder.Entity("FallenFaction.Server.Data.Models.Publisher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RejectedTitleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RejectedTitleId");

                    b.ToTable("Publishers");
                });

            modelBuilder.Entity("FallenFaction.Server.Data.Models.Rating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("TitleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TitleId");

                    b.HasIndex("UserId");

                    b.ToTable("Ratings");
                });

            modelBuilder.Entity("FallenFaction.Server.Data.Models.RejectedChapter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChapterNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.Property<int>("TitleId")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedByUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("VolumeNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.HasIndex("TitleId");

                    b.HasIndex("UpdatedByUserId");

                    b.ToTable("RejectedChapters");
                });

            modelBuilder.Entity("FallenFaction.Server.Data.Models.RejectedTitle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AgeRestriction")
                        .HasColumnType("int");

                    b.Property<string>("AlternativeNames")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BackgroundImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoverImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnglishTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExternalLinksSerialized")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OriginalTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReleaseDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatusTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatusTranslation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("RejectedTitles");
                });

            modelBuilder.Entity("FallenFaction.Server.Data.Models.RejectedTitleChange", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdminComment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChangeType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("NewValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RejectedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RejectionReason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReviewedByUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("TitleId")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedByUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ReviewedByUserId");

                    b.HasIndex("TitleId");

                    b.HasIndex("UpdatedByUserId");

                    b.ToTable("RejectedTitleChanges");
                });

            modelBuilder.Entity("FallenFaction.Server.Data.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RejectedTitleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RejectedTitleId");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Fantasy"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Magic"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Mystery"
                        });
                });

            modelBuilder.Entity("FallenFaction.Server.Data.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("RejectedTitleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RejectedTitleId");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("FallenFaction.Server.Data.Models.Title", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdminComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AgeRestriction")
                        .HasColumnType("int");

                    b.Property<string>("AlternativeNames")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("AreChapterCommentsEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("AreCommentsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("BackgroundImagePath")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("CoverImagePath")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnglishTitle")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ExternalLinksSerialized")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("OriginalTitle")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ReleaseDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatusTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatusTranslation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Titles");
                });

            modelBuilder.Entity("FallenFaction.Server.Data.Models.TitleChangeLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdminComment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChangeType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("NewValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReviewedByUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TitleId")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedByUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ReviewedByUserId");

                    b.HasIndex("TitleId");

                    b.HasIndex("UpdatedByUserId");

                    b.ToTable("TitleChangeLogs");
                });

            modelBuilder.Entity("FallenFaction.Server.Data.Models.UserTeamPermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PermissionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserTeamPermissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PermissionName = "CanAddTitle"
                        },
                        new
                        {
                            Id = 2,
                            PermissionName = "CanDeleteTitle"
                        },
                        new
                        {
                            Id = 3,
                            PermissionName = "CanEditTitle"
                        },
                        new
                        {
                            Id = 4,
                            PermissionName = "CanAddMember"
                        },
                        new
                        {
                            Id = 5,
                            PermissionName = "CanRemoveMember"
                        });
                });

            modelBuilder.Entity("FallenFaction.Server.Data.Models.UserTeamRole", b =>
                {
                    b.Property<string>("AppUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("AppUserId", "TeamId");

                    b.HasIndex("TeamId");

                    b.ToTable("UserTeamRoles");
                });

            modelBuilder.Entity("FallenFaction.Server.Data.Models.UserTeamRolePermission", b =>
                {
                    b.Property<string>("AppUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.HasKey("AppUserId", "TeamId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("UserTeamRolePermission");
                });

            modelBuilder.Entity("FormatPendingTitle", b =>
                {
                    b.Property<int>("FormatsId")
                        .HasColumnType("int");

                    b.Property<int>("PendingTitlesId")
                        .HasColumnType("int");

                    b.HasKey("FormatsId", "PendingTitlesId");

                    b.HasIndex("PendingTitlesId");

                    b.ToTable("PendingTitleFormats", (string)null);
                });

            modelBuilder.Entity("FormatTitle", b =>
                {
                    b.Property<int>("FormatsId")
                        .HasColumnType("int");

                    b.Property<int>("TitlesId")
                        .HasColumnType("int");

                    b.HasKey("FormatsId", "TitlesId");

                    b.HasIndex("TitlesId");

                    b.ToTable("TitleFormats", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("PendingTitlePublisher", b =>
                {
                    b.Property<int>("PendingTitlesId")
                        .HasColumnType("int");

                    b.Property<int>("PublishersId")
                        .HasColumnType("int");

                    b.HasKey("PendingTitlesId", "PublishersId");

                    b.HasIndex("PublishersId");

                    b.ToTable("PendingTitlePublishers", (string)null);
                });

            modelBuilder.Entity("PendingTitleTag", b =>
                {
                    b.Property<int>("PendingTitlesId")
                        .HasColumnType("int");

                    b.Property<int>("TagsId")
                        .HasColumnType("int");

                    b.HasKey("PendingTitlesId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("PendingTitleTags", (string)null);
                });

            modelBuilder.Entity("PendingTitleTeam", b =>
                {
                    b.Property<int>("PendingTitlesId")
                        .HasColumnType("int");

                    b.Property<int>("TeamsId")
                        .HasColumnType("int");

                    b.HasKey("PendingTitlesId", "TeamsId");

                    b.HasIndex("TeamsId");

                    b.ToTable("PendingTitleTeams", (string)null);
                });

            modelBuilder.Entity("PublisherTitle", b =>
                {
                    b.Property<int>("PublishersId")
                        .HasColumnType("int");

                    b.Property<int>("TitlesId")
                        .HasColumnType("int");

                    b.HasKey("PublishersId", "TitlesId");

                    b.HasIndex("TitlesId");

                    b.ToTable("TitlePublishers", (string)null);
                });

            modelBuilder.Entity("TagTitle", b =>
                {
                    b.Property<int>("TagsId")
                        .HasColumnType("int");

                    b.Property<int>("TitlesId")
                        .HasColumnType("int");

                    b.HasKey("TagsId", "TitlesId");

                    b.HasIndex("TitlesId");

                    b.ToTable("TitleTags", (string)null);
                });

            modelBuilder.Entity("TeamTitle", b =>
                {
                    b.Property<int>("TeamsId")
                        .HasColumnType("int");

                    b.Property<int>("TitlesId")
                        .HasColumnType("int");

                    b.HasKey("TeamsId", "TitlesId");

                    b.HasIndex("TitlesId");

                    b.ToTable("TitleTeams", (string)null);
                });

            modelBuilder.Entity("AppUserTeam", b =>
                {
                    b.HasOne("FallenFaction.Server.Data.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("MembersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FallenFaction.Server.Data.Models.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ArtistPendingTitle", b =>
                {
                    b.HasOne("FallenFaction.Server.Data.Models.Artist", null)
                        .WithMany()
                        .HasForeignKey("ArtistsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FallenFaction.Server.Data.Models.PendingTitle", null)
                        .WithMany()
                        .HasForeignKey("PendingTitlesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ArtistTitle", b =>
                {
                    b.HasOne("FallenFaction.Server.Data.Models.Artist", null)
                        .WithMany()
                        .HasForeignKey("ArtistsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FallenFaction.Server.Data.Models.Title", null)
                        .WithMany()
                        .HasForeignKey("TitlesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AuthorPendingTitle", b =>
                {
                    b.HasOne("FallenFaction.Server.Data.Models.Author", null)
                        .WithMany()
                        .HasForeignKey("AuthorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FallenFaction.Server.Data.Models.PendingTitle", null)
                        .WithMany()
                        .HasForeignKey("PendingTitlesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AuthorTitle", b =>
                {
                    b.HasOne("FallenFaction.Server.Data.Models.Author", null)
                        .WithMany()
                        .HasForeignKey("AuthorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FallenFaction.Server.Data.Models.Title", null)
                        .WithMany()
                        .HasForeignKey("TitlesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CategoryPendingTitle", b =>
                {
                    b.HasOne("FallenFaction.Server.Data.Models.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FallenFaction.Server.Data.Models.PendingTitle", null)
                        .WithMany()
                        .HasForeignKey("PendingTitlesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CategoryTitle", b =>
                {
                    b.HasOne("FallenFaction.Server.Data.Models.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FallenFaction.Server.Data.Models.Title", null)
                        .WithMany()
                        .HasForeignKey("TitlesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FallenFaction.Server.Data.Models.ApprovedTitleChange", b =>
                {
                    b.HasOne("FallenFaction.Server.Data.Models.AppUser", "ReviewedByUser")
                        .WithMany()
                        .HasForeignKey("ReviewedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FallenFaction.Server.Data.Models.Title", "Title")
                        .WithMany("ApprovedTitleChanges")
                        .HasForeignKey("TitleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FallenFaction.Server.Data.Models.AppUser", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ReviewedByUser");

                    b.Navigation("Title");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("FallenFaction.Server.Data.Models.Artist", b =>
                {
                    b.HasOne("FallenFaction.Server.Data.Models.RejectedTitle", null)
                        .WithMany("Artists")
                        .HasForeignKey("RejectedTitleId");
                });

            modelBuilder.Entity("FallenFaction.Server.Data.Models.Author", b =>
                {
                    b.HasOne("FallenFaction.Server.Data.Models.RejectedTitle", null)
                        .WithMany("Authors")
                        .HasForeignKey("RejectedTitleId");
                });

            modelBuilder.Entity("FallenFaction.Server.Data.Models.Bookmark", b =>
                {
                    b.HasOne("FallenFaction.Server.Data.Models.BookmarkFolder", "Folder")
                        .WithMany("Bookmarks")
                        .HasForeignKey("FolderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FallenFaction.Server.Data.Models.Title", "Title")
                        .WithMany("Bookmarks")
                        .HasForeignKey("TitleId")
                        .IsRequired();

                    b.HasOne("FallenFaction.Server.Data.Models.AppUser", "User")
                        .WithMany("Bookmarks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Folder");

                    b.Navigation("Title");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FallenFaction.Server.Data.Models.BookmarkFolder", b =>
                {
                    b.HasOne("FallenFaction.Server.Data.Models.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FallenFaction.Server.Data.Models.Category", b =>
                {
                    b.HasOne("FallenFaction.Server.Data.Models.RejectedTitle", null)
                        .WithMany("Categories")
                        .HasForeignKey("RejectedTitleId");
                });

            modelBuilder.Entity("FallenFaction.Server.Data.Models.Chapter", b =>
                {
                    b.HasOne("FallenFaction.Server.Data.Models.Team", "Team")
                        .WithMany("Chapters")
                        .HasForeignKey("TeamId");

                    b.HasOne("FallenFaction.Server.Data.Models.Title", "Title")
                        .WithMany("Chapters")
                        .HasForeignKey("TitleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FallenFaction.Server.Data.Models.AppUser", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");

                    b.Navigation("Title");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("FallenFaction.Server.Data.Models.ChapterImage", b =>
                {
                    b.HasOne("FallenFaction.Server.Data.Models.Chapter", "Chapter")
                        .WithMany("ImagePaths")
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("FallenFaction.Server.Data.Models.PendingChapter", "PendingChapter")
                        .WithMany("ImagePaths")
                        .HasForeignKey("PendingChapterId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("FallenFaction.Server.Data.Models.RejectedChapter", "RejectedChapter")
                        .WithMany("ImagePaths")
                        .HasForeignKey("RejectedChapterId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Chapter");

                    b.Navigation("PendingChapter");

                    b.Navigation("RejectedChapter");
                });

            modelBuilder.Entity("FallenFaction.Server.Data.Models.ChapterView", b =>
                {
                    b.HasOne("FallenFaction.Server.Data.Models.Chapter", "Chapter")
                        .WithMany("Views")
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FallenFaction.Server.Data.Models.AppUser", "User")
                        .WithMany("ChapterViews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chapter");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FallenFaction.Server.Data.Models.Comment", b =>
                {
                    b.HasOne("FallenFaction.Server.Data.Models.Chapter", "Chapter")
                        .WithMany()
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("FallenFaction.Server.Data.Models.ChapterImage", "ChapterImage")
                        .WithMany()
                        .HasForeignKey("ChapterImageId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("FallenFaction.Server.Data.Models.Comment", "ParentComment")
                        .WithMany("Replies")
                        .HasForeignKey("ParentCommentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FallenFaction.Server.Data.Models.Title", "Title")
                        .WithMany("Comments")
                        .HasForeignKey("TitleId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("FallenFaction.Server.Data.Models.AppUser", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Chapter");

                    b.Navigation("ChapterImage");

                    b.Navigation("ParentComment");

                    b.Navigation("Title");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FallenFaction.Server.Data.Models.CommentReaction", b =>
                {
                    b.HasOne("FallenFaction.Server.Data.Models.Comment", "Comment")
                        .WithMany("Reactions")
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FallenFaction.Server.Data.Models.AppUser", "User")
                        .WithMany("CommentReactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FallenFaction.Server.Data.Models.Format", b =>
                {
                    b.HasOne("FallenFaction.Server.Data.Models.RejectedTitle", null)
                        .WithMany("Formats")
                        .HasForeignKey("RejectedTitleId");
                });

            modelBuilder.Entity("FallenFaction.Server.Data.Models.PendingChapter", b =>
                {
                    b.HasOne("FallenFaction.Server.Data.Models.Team", "Team")
                        .WithMany("PendingChapters")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FallenFaction.Server.Data.Models.Title", "Title")
                        .WithMany("PendingChapters")
                        .HasForeignKey("TitleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FallenFaction.Server.Data.Models.AppUser", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");

                    b.Navigation("Title");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("FallenFaction.Server.Data.Models.PendingTitleChange", b =>
                {
                    b.HasOne("FallenFaction.Server.Data.Models.Title", "Title")
                        .WithMany("PendingTitleChanges")
                        .HasForeignKey("TitleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FallenFaction.Server.Data.Models.AppUser", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Title");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("FallenFaction.Server.Data.Models.Publisher", b =>
                {
                    b.HasOne("FallenFaction.Server.Data.Models.RejectedTitle", null)
                        .WithMany("Publishers")
                        .HasForeignKey("RejectedTitleId");
                });

            modelBuilder.Entity("FallenFaction.Server.Data.Models.Rating", b =>
                {
                    b.HasOne("FallenFaction.Server.Data.Models.Title", "Title")
                        .WithMany("Ratings")
                        .HasForeignKey("TitleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FallenFaction.Server.Data.Models.AppUser", "User")
                        .WithMany("Ratings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Title");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FallenFaction.Server.Data.Models.RejectedChapter", b =>
                {
                    b.HasOne("FallenFaction.Server.Data.Models.Team", "Team")
                        .WithMany("RejectedChapters")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FallenFaction.Server.Data.Models.Title", "Title")
                        .WithMany("RejectedChapters")
                        .HasForeignKey("TitleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FallenFaction.Server.Data.Models.AppUser", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");

                    b.Navigation("Title");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("FallenFaction.Server.Data.Models.RejectedTitleChange", b =>
                {
                    b.HasOne("FallenFaction.Server.Data.Models.AppUser", "ReviewedByUser")
                        .WithMany()
                        .HasForeignKey("ReviewedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FallenFaction.Server.Data.Models.Title", "Title")
                        .WithMany("RejectedTitleChanges")
                        .HasForeignKey("TitleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FallenFaction.Server.Data.Models.AppUser", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ReviewedByUser");

                    b.Navigation("Title");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("FallenFaction.Server.Data.Models.Tag", b =>
                {
                    b.HasOne("FallenFaction.Server.Data.Models.RejectedTitle", null)
                        .WithMany("Tags")
                        .HasForeignKey("RejectedTitleId");
                });

            modelBuilder.Entity("FallenFaction.Server.Data.Models.Team", b =>
                {
                    b.HasOne("FallenFaction.Server.Data.Models.RejectedTitle", null)
                        .WithMany("Teams")
                        .HasForeignKey("RejectedTitleId");
                });

            modelBuilder.Entity("FallenFaction.Server.Data.Models.TitleChangeLog", b =>
                {
                    b.HasOne("FallenFaction.Server.Data.Models.AppUser", "ReviewedByUser")
                        .WithMany()
                        .HasForeignKey("ReviewedByUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("FallenFaction.Server.Data.Models.Title", "Title")
                        .WithMany("ChangeLogs")
                        .HasForeignKey("TitleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FallenFaction.Server.Data.Models.AppUser", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ReviewedByUser");

                    b.Navigation("Title");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("FallenFaction.Server.Data.Models.UserTeamRole", b =>
                {
                    b.HasOne("FallenFaction.Server.Data.Models.AppUser", "AppUser")
                        .WithMany("UserTeamRoles")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FallenFaction.Server.Data.Models.Team", "Team")
                        .WithMany("UserTeamRoles")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("FallenFaction.Server.Data.Models.UserTeamRolePermission", b =>
                {
                    b.HasOne("FallenFaction.Server.Data.Models.UserTeamPermission", "UserTeamPermission")
                        .WithMany("UserTeamRolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FallenFaction.Server.Data.Models.UserTeamRole", "UserTeamRole")
                        .WithMany("UserTeamRolePermissions")
                        .HasForeignKey("AppUserId", "TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserTeamPermission");

                    b.Navigation("UserTeamRole");
                });

            modelBuilder.Entity("FormatPendingTitle", b =>
                {
                    b.HasOne("FallenFaction.Server.Data.Models.Format", null)
                        .WithMany()
                        .HasForeignKey("FormatsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FallenFaction.Server.Data.Models.PendingTitle", null)
                        .WithMany()
                        .HasForeignKey("PendingTitlesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FormatTitle", b =>
                {
                    b.HasOne("FallenFaction.Server.Data.Models.Format", null)
                        .WithMany()
                        .HasForeignKey("FormatsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FallenFaction.Server.Data.Models.Title", null)
                        .WithMany()
                        .HasForeignKey("TitlesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("FallenFaction.Server.Data.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("FallenFaction.Server.Data.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FallenFaction.Server.Data.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("FallenFaction.Server.Data.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PendingTitlePublisher", b =>
                {
                    b.HasOne("FallenFaction.Server.Data.Models.PendingTitle", null)
                        .WithMany()
                        .HasForeignKey("PendingTitlesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FallenFaction.Server.Data.Models.Publisher", null)
                        .WithMany()
                        .HasForeignKey("PublishersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PendingTitleTag", b =>
                {
                    b.HasOne("FallenFaction.Server.Data.Models.PendingTitle", null)
                        .WithMany()
                        .HasForeignKey("PendingTitlesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FallenFaction.Server.Data.Models.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PendingTitleTeam", b =>
                {
                    b.HasOne("FallenFaction.Server.Data.Models.PendingTitle", null)
                        .WithMany()
                        .HasForeignKey("PendingTitlesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FallenFaction.Server.Data.Models.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PublisherTitle", b =>
                {
                    b.HasOne("FallenFaction.Server.Data.Models.Publisher", null)
                        .WithMany()
                        .HasForeignKey("PublishersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FallenFaction.Server.Data.Models.Title", null)
                        .WithMany()
                        .HasForeignKey("TitlesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TagTitle", b =>
                {
                    b.HasOne("FallenFaction.Server.Data.Models.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FallenFaction.Server.Data.Models.Title", null)
                        .WithMany()
                        .HasForeignKey("TitlesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TeamTitle", b =>
                {
                    b.HasOne("FallenFaction.Server.Data.Models.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FallenFaction.Server.Data.Models.Title", null)
                        .WithMany()
                        .HasForeignKey("TitlesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FallenFaction.Server.Data.Models.AppUser", b =>
                {
                    b.Navigation("Bookmarks");

                    b.Navigation("ChapterViews");

                    b.Navigation("CommentReactions");

                    b.Navigation("Comments");

                    b.Navigation("Ratings");

                    b.Navigation("UserTeamRoles");
                });

            modelBuilder.Entity("FallenFaction.Server.Data.Models.BookmarkFolder", b =>
                {
                    b.Navigation("Bookmarks");
                });

            modelBuilder.Entity("FallenFaction.Server.Data.Models.Chapter", b =>
                {
                    b.Navigation("ImagePaths");

                    b.Navigation("Views");
                });

            modelBuilder.Entity("FallenFaction.Server.Data.Models.Comment", b =>
                {
                    b.Navigation("Reactions");

                    b.Navigation("Replies");
                });

            modelBuilder.Entity("FallenFaction.Server.Data.Models.PendingChapter", b =>
                {
                    b.Navigation("ImagePaths");
                });

            modelBuilder.Entity("FallenFaction.Server.Data.Models.RejectedChapter", b =>
                {
                    b.Navigation("ImagePaths");
                });

            modelBuilder.Entity("FallenFaction.Server.Data.Models.RejectedTitle", b =>
                {
                    b.Navigation("Artists");

                    b.Navigation("Authors");

                    b.Navigation("Categories");

                    b.Navigation("Formats");

                    b.Navigation("Publishers");

                    b.Navigation("Tags");

                    b.Navigation("Teams");
                });

            modelBuilder.Entity("FallenFaction.Server.Data.Models.Team", b =>
                {
                    b.Navigation("Chapters");

                    b.Navigation("PendingChapters");

                    b.Navigation("RejectedChapters");

                    b.Navigation("UserTeamRoles");
                });

            modelBuilder.Entity("FallenFaction.Server.Data.Models.Title", b =>
                {
                    b.Navigation("ApprovedTitleChanges");

                    b.Navigation("Bookmarks");

                    b.Navigation("ChangeLogs");

                    b.Navigation("Chapters");

                    b.Navigation("Comments");

                    b.Navigation("PendingChapters");

                    b.Navigation("PendingTitleChanges");

                    b.Navigation("Ratings");

                    b.Navigation("RejectedChapters");

                    b.Navigation("RejectedTitleChanges");
                });

            modelBuilder.Entity("FallenFaction.Server.Data.Models.UserTeamPermission", b =>
                {
                    b.Navigation("UserTeamRolePermissions");
                });

            modelBuilder.Entity("FallenFaction.Server.Data.Models.UserTeamRole", b =>
                {
                    b.Navigation("UserTeamRolePermissions");
                });
#pragma warning restore 612, 618
        }
    }
}
