// <auto-generated />
using System;
using FallenFaction.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FallenFaction.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260331000001_AddOriginalChapterIdToPendingChapter")]
    partial class AddOriginalChapterIdToPendingChapter
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Snapshot handled by ApplicationDbContextModelSnapshot.cs
        }
    }
}
